name: Monitor official website
on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Change directory
      run: cd ./monitor

    - name: Install dependencies
      run: |
        npm install

    - name: Execute monitor:check
      run: npm run monitor:check