name: Monitor official website
on: 
  schedule:
   - cron: "*/5 * * * *"

jobs:
  monitor-official-website:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install dependencies
      run: npm install
      working-directory: ./monitor

    - name: Execute monitor:check
      run: npm run monitor:check
      working-directory: ./monitor